// <auto-generated />
using System;
using Cms.RouteService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cms.RouteService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RouteDbContext))]
    partial class RouteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cms-route-service")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cms.RouteService.Domain.Entities.BaseRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Cms.RouteService.Domain.Entities.PostRoute", b =>
                {
                    b.HasBaseType("Cms.RouteService.Domain.Entities.BaseRoute");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_post_route___path");

                    b.ToTable("post_route", "cms-route-service");
                });

            modelBuilder.Entity("Cms.RouteService.Domain.Entities.TopicRoute", b =>
                {
                    b.HasBaseType("Cms.RouteService.Domain.Entities.BaseRoute");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("IX_topic_route___path");

                    b.ToTable("topic_route", "cms-route-service");
                });
#pragma warning restore 612, 618
        }
    }
}
